version: 2

builds:
  - main: .
    binary: elevencli
    ldflags:
      - -s -w -X github.com/deegital/elevencli/cmd.version={{.Version}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

brews:
  - repository:
      owner: deegital
      name: homebrew-tap
    homepage: "https://github.com/deegital/elevencli"
    description: "ElevenLabs CLI — text-to-speech and sound effects from the command line"
    license: "MIT"
    install: |
      bin.install "elevencli"
    test: |
      system "#{bin}/elevencli", "--version"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^style:"
      - "^test:"
